export const PERMISSIONS = {
  DASHBOARD_VIEW: "dashboard.view",

  COURSES_VIEW: "courses.view",
  COURSES_CREATE: "courses.create",
  COURSES_EDIT: "courses.edit",
  COURSES_DELETE: "courses.delete",

  FACULTY_VIEW: "faculty.view",
  FACULTY_CREATE: "faculty.create",
  FACULTY_EDIT: "faculty.edit",
  FACULTY_DELETE: "faculty.delete",

  SUBJECTS_VIEW: "subjects.view",
  SUBJECTS_CREATE: "subjects.create",
  SUBJECTS_EDIT: "subjects.edit",
  SUBJECTS_DELETE: "subjects.delete",

  BATCHES_VIEW: "batches.view",
  BATCHES_CREATE: "batches.create",
  BATCHES_EDIT: "batches.edit",
  BATCHES_DELETE: "batches.delete",

  SCHEDULE_VIEW: "schedule.view",
  SCHEDULE_CREATE: "schedule.create",
  SCHEDULE_EDIT: "schedule.edit",
  SCHEDULE_DELETE: "schedule.delete",

  RESULTS_VIEW: "results.view",
  RESULTS_CREATE: "results.create",
  RESULTS_EDIT: "results.edit",
  RESULTS_DELETE: "results.delete",

  ENQUIRIES_VIEW: "enquiries.view",
  ENQUIRIES_CREATE: "enquiries.create",
  ENQUIRIES_EDIT: "enquiries.edit",
  ENQUIRIES_DELETE: "enquiries.delete",

  ANNOUNCEMENTS_VIEW: "announcements.view",
  ANNOUNCEMENTS_CREATE: "announcements.create",
  ANNOUNCEMENTS_EDIT: "announcements.edit",
  ANNOUNCEMENTS_DELETE: "announcements.delete",

  GALLERY_VIEW: "gallery.view",
  GALLERY_UPLOAD: "gallery.upload",
  GALLERY_DELETE: "gallery.delete",

  TESTIMONIALS_VIEW: "testimonials.view",
  TESTIMONIALS_CREATE: "testimonials.create",
  TESTIMONIALS_EDIT: "testimonials.edit",
  TESTIMONIALS_DELETE: "testimonials.delete",

  FAQ_VIEW: "faq.view",
  FAQ_CREATE: "faq.create",
  FAQ_EDIT: "faq.edit",
  FAQ_DELETE: "faq.delete",

  BRANCHES_VIEW: "branches.view",
  BRANCHES_CREATE: "branches.create",
  BRANCHES_EDIT: "branches.edit",
  BRANCHES_DELETE: "branches.delete",

  SETTINGS_VIEW: "settings.view",
  SETTINGS_EDIT: "settings.edit",

  USERS_VIEW: "users.view",
  USERS_CREATE: "users.create",
  USERS_EDIT: "users.edit",

  LOGS_VIEW: "logs.view",

  STORAGE_UPLOAD: "storage.upload",
  STORAGE_DELETE: "storage.delete",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ALL_PERMISSIONS: Permission[] = [
  PERMISSIONS.DASHBOARD_VIEW,

  PERMISSIONS.COURSES_VIEW,
  PERMISSIONS.COURSES_CREATE,
  PERMISSIONS.COURSES_EDIT,
  PERMISSIONS.COURSES_DELETE,

  PERMISSIONS.FACULTY_VIEW,
  PERMISSIONS.FACULTY_CREATE,
  PERMISSIONS.FACULTY_EDIT,
  PERMISSIONS.FACULTY_DELETE,

  PERMISSIONS.SUBJECTS_VIEW,
  PERMISSIONS.SUBJECTS_CREATE,
  PERMISSIONS.SUBJECTS_EDIT,
  PERMISSIONS.SUBJECTS_DELETE,

  PERMISSIONS.BATCHES_VIEW,
  PERMISSIONS.BATCHES_CREATE,
  PERMISSIONS.BATCHES_EDIT,
  PERMISSIONS.BATCHES_DELETE,

  PERMISSIONS.SCHEDULE_VIEW,
  PERMISSIONS.SCHEDULE_CREATE,
  PERMISSIONS.SCHEDULE_EDIT,
  PERMISSIONS.SCHEDULE_DELETE,

  PERMISSIONS.RESULTS_VIEW,
  PERMISSIONS.RESULTS_CREATE,
  PERMISSIONS.RESULTS_EDIT,
  PERMISSIONS.RESULTS_DELETE,

  PERMISSIONS.ENQUIRIES_VIEW,
  PERMISSIONS.ENQUIRIES_CREATE,
  PERMISSIONS.ENQUIRIES_EDIT,
  PERMISSIONS.ENQUIRIES_DELETE,

  PERMISSIONS.ANNOUNCEMENTS_VIEW,
  PERMISSIONS.ANNOUNCEMENTS_CREATE,
  PERMISSIONS.ANNOUNCEMENTS_EDIT,
  PERMISSIONS.ANNOUNCEMENTS_DELETE,

  PERMISSIONS.GALLERY_VIEW,
  PERMISSIONS.GALLERY_UPLOAD,
  PERMISSIONS.GALLERY_DELETE,

  PERMISSIONS.TESTIMONIALS_VIEW,
  PERMISSIONS.TESTIMONIALS_CREATE,
  PERMISSIONS.TESTIMONIALS_EDIT,
  PERMISSIONS.TESTIMONIALS_DELETE,

  PERMISSIONS.FAQ_VIEW,
  PERMISSIONS.FAQ_CREATE,
  PERMISSIONS.FAQ_EDIT,
  PERMISSIONS.FAQ_DELETE,

  PERMISSIONS.BRANCHES_VIEW,
  PERMISSIONS.BRANCHES_CREATE,
  PERMISSIONS.BRANCHES_EDIT,
  PERMISSIONS.BRANCHES_DELETE,

  PERMISSIONS.SETTINGS_VIEW,
  PERMISSIONS.SETTINGS_EDIT,

  PERMISSIONS.USERS_VIEW,
  PERMISSIONS.USERS_CREATE,
  PERMISSIONS.USERS_EDIT,

  PERMISSIONS.LOGS_VIEW,

  PERMISSIONS.STORAGE_UPLOAD,
  PERMISSIONS.STORAGE_DELETE,
];

/**
 * Baseline granted to every STAFF account (and re-applied whenever an
 * account is demoted to staff). Keeps profiles.role and user_permissions
 * consistent — the role alone never decides access.
 */
export const STAFF_DEFAULT_PERMISSIONS: Permission[] = [
  PERMISSIONS.DASHBOARD_VIEW,
  PERMISSIONS.COURSES_VIEW,
  PERMISSIONS.FACULTY_VIEW,
  PERMISSIONS.SUBJECTS_VIEW,
  PERMISSIONS.BATCHES_VIEW,
  PERMISSIONS.SCHEDULE_VIEW,
  PERMISSIONS.RESULTS_VIEW,
  PERMISSIONS.ENQUIRIES_VIEW,
  PERMISSIONS.ENQUIRIES_EDIT,
  PERMISSIONS.ANNOUNCEMENTS_VIEW,
  PERMISSIONS.GALLERY_VIEW,
  PERMISSIONS.TESTIMONIALS_VIEW,
  PERMISSIONS.FAQ_VIEW,
  PERMISSIONS.BRANCHES_VIEW,
  PERMISSIONS.STORAGE_UPLOAD,
];

/** ADMIN receives the full permission set; it can still be narrowed later. */
export const ADMIN_DEFAULT_PERMISSIONS: Permission[] = [...ALL_PERMISSIONS];

export function defaultPermissionsForRole(role: string): string[] {
  if (role === "owner") return [...ALL_PERMISSIONS];
  if (role === "admin") return [...ADMIN_DEFAULT_PERMISSIONS];
  return [...STAFF_DEFAULT_PERMISSIONS];
}

export const PERMISSION_GROUPS: { label: string; permissions: Permission[] }[] = [
  { label: "Dashboard", permissions: [PERMISSIONS.DASHBOARD_VIEW] },
  {
    label: "Courses",
    permissions: [
      PERMISSIONS.COURSES_VIEW,
      PERMISSIONS.COURSES_CREATE,
      PERMISSIONS.COURSES_EDIT,
      PERMISSIONS.COURSES_DELETE,
    ],
  },
  {
    label: "Faculty",
    permissions: [
      PERMISSIONS.FACULTY_VIEW,
      PERMISSIONS.FACULTY_CREATE,
      PERMISSIONS.FACULTY_EDIT,
      PERMISSIONS.FACULTY_DELETE,
    ],
  },
  {
    label: "Subjects",
    permissions: [
      PERMISSIONS.SUBJECTS_VIEW,
      PERMISSIONS.SUBJECTS_CREATE,
      PERMISSIONS.SUBJECTS_EDIT,
      PERMISSIONS.SUBJECTS_DELETE,
    ],
  },
  {
    label: "Batches",
    permissions: [
      PERMISSIONS.BATCHES_VIEW,
      PERMISSIONS.BATCHES_CREATE,
      PERMISSIONS.BATCHES_EDIT,
      PERMISSIONS.BATCHES_DELETE,
    ],
  },
  {
    label: "Schedule",
    permissions: [
      PERMISSIONS.SCHEDULE_VIEW,
      PERMISSIONS.SCHEDULE_CREATE,
      PERMISSIONS.SCHEDULE_EDIT,
      PERMISSIONS.SCHEDULE_DELETE,
    ],
  },
  {
    label: "Results",
    permissions: [
      PERMISSIONS.RESULTS_VIEW,
      PERMISSIONS.RESULTS_CREATE,
      PERMISSIONS.RESULTS_EDIT,
      PERMISSIONS.RESULTS_DELETE,
    ],
  },
  {
    label: "Enquiries",
    permissions: [
      PERMISSIONS.ENQUIRIES_VIEW,
      PERMISSIONS.ENQUIRIES_CREATE,
      PERMISSIONS.ENQUIRIES_EDIT,
      PERMISSIONS.ENQUIRIES_DELETE,
    ],
  },
  {
    label: "Announcements",
    permissions: [
      PERMISSIONS.ANNOUNCEMENTS_VIEW,
      PERMISSIONS.ANNOUNCEMENTS_CREATE,
      PERMISSIONS.ANNOUNCEMENTS_EDIT,
      PERMISSIONS.ANNOUNCEMENTS_DELETE,
    ],
  },
  {
    label: "Gallery",
    permissions: [
      PERMISSIONS.GALLERY_VIEW,
      PERMISSIONS.GALLERY_UPLOAD,
      PERMISSIONS.GALLERY_DELETE,
    ],
  },
  {
    label: "Testimonials",
    permissions: [
      PERMISSIONS.TESTIMONIALS_VIEW,
      PERMISSIONS.TESTIMONIALS_CREATE,
      PERMISSIONS.TESTIMONIALS_EDIT,
      PERMISSIONS.TESTIMONIALS_DELETE,
    ],
  },
  {
    label: "FAQ",
    permissions: [PERMISSIONS.FAQ_VIEW, PERMISSIONS.FAQ_CREATE, PERMISSIONS.FAQ_EDIT, PERMISSIONS.FAQ_DELETE],
  },
  {
    label: "Branches",
    permissions: [
      PERMISSIONS.BRANCHES_VIEW,
      PERMISSIONS.BRANCHES_CREATE,
      PERMISSIONS.BRANCHES_EDIT,
      PERMISSIONS.BRANCHES_DELETE,
    ],
  },
  { label: "Settings", permissions: [PERMISSIONS.SETTINGS_VIEW, PERMISSIONS.SETTINGS_EDIT] },
  {
    label: "Users",
    permissions: [PERMISSIONS.USERS_VIEW, PERMISSIONS.USERS_CREATE, PERMISSIONS.USERS_EDIT],
  },
  { label: "Audit Logs", permissions: [PERMISSIONS.LOGS_VIEW] },
  {
    label: "Storage",
    permissions: [PERMISSIONS.STORAGE_UPLOAD, PERMISSIONS.STORAGE_DELETE],
  },
];
